version: '2'
services:
  upz_packets_routes_Africa:
    build: ./upz_packets_routes_Africa
    #network_mode: "host"
    # No ports need to be exposed for the client
    restart: always
    volumes:
      - 'pr_data:/reports' #packets_routes_data
  upz_mesh_routes:
    build: ./upz_mesh_routes
    #network_mode: "host"
    # No ports need to be exposed for the client
    restart: always
    volumes:
      - 'ms_data:/reports' #packets_routes_data
 
  upz_web_perfomance_measurements:
    build: ./upz_web_perfomance_measurements
    restart: always
    volumes:
      - 'wm_data:/reports' #web_measurement_data

  upz_iperf3-server:
    build: ./upz_iperf3-server
    network_mode: "host"
    ports:
      - "5201:5201" # Default iPerf3 server port
    restart: always

  upz_iperf3-client:
    build: ./upz_iperf3-client
    environment:
      - IPERF3_TARGET=your_public_url
    volumes:
      - 'iprf_data:/reports'
    restart: always

volumes:
  pr_data:
  ms_data:
  wm_data:
  iprf_data: