version: '2'
services:
  iperf3-server:
    build: ./iperf3-server
    ports:
      - "5201:5201" # Default iPerf3 server port
    restart: always

  measurements:
    build: ./measurements
    # No ports need to be exposed for the client
    restart: always
